### ISSUE TITLE
Implement SFX banks as a resource rather than a hardcoded dictionary

### ISSUE THREAD

**Issue by GTcreyon** [GTcreyon/SM63Redux#251] opened 2023-09-20 09:33 UTC
**Describe the feature you'd like**
The SFX_BANK in player.gd is enormous, full of hardcoded inflexible file paths, and makes the rest of the script hard to read. It could easily be replaced with a resource file with dynamic UID (export var) references to solve both of these problems, and make it more designer-friendly.

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
Probably. It will likely coincide and intersect with #244, so that should be handled with care, although these issues are not mutually dependent.

**Comment by Koopa1018** [comment] 2023-09-22 06:57
Duplicate of #108.

**Closed by Koopa1018** 2023-09-22 06:57 UTC
Labels: duplicate, refactor, audio
