### ISSUE TITLE
Touch Controls are too small

### ISSUE THREAD

**Issue by ChaseyBOI801** [GTcreyon/SM63Redux#34] opened 2023-01-05 23:36 UTC
**Describe the feature you'd like**
The Jump button on mobile is the up button, but the right button is right next to it and it's so small, that I can't jump and move easily. 
can you add like a button on the left side so mobile players can jump. Thanks.

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
I am lost on how to code in GD script.

**Comment by GTcreyon** [comment] 2023-01-05 23:38
Duplicate of #32.

**Closed by GTcreyon** 2023-01-05 23:38 UTC
