### ISSUE TITLE
Spin + killing a fish results in a game crash + godot opening up

### ISSUE THREAD

**Issue by thebugwitch** [GTcreyon/SM63Redux#4] opened 2022-08-31 12:25 UTC
**Describe the bug**
Attempted spin attack on a fish, it made the Godot menu pop up explaining the bug error saying "Invalid get index '13' (on base: 'Array')."

**To Reproduce**
Spin and hit a fish

**Expected behavior**
Spin and hit fish, it hits fish back

**Screenshots**
[Here](https://user-images.githubusercontent.com/87394133/187677464-db2eb04f-8b27-4257-98d4-b0327f1d710e.png)

**System Information**
 - OS: Arch Linux, Latest Stable
 - Game version: Latest

**Comment by GTcreyon** [comment] 2022-08-31 12:27
Looking at the error that shows up, it would seem that this is an issue with pickup IDs. Possibly a mistake with how they're assigned - might be cheep cheep specific.

**Comment by GTcreyon** [comment] 2022-08-31 17:25
Currently unable to reproduce the issue, but, the pickup ID server is pretty outdated, so I think I'll probably fix it while I go through updating it.

**Comment by GTcreyon** [comment] 2022-09-03 14:47
Closed by 612e5bb.

**Closed by GTcreyon** 2022-09-03 14:47 UTC
Labels: bug
